ALTER TABLE users ADD COLUMN plan_type VARCHAR(50) DEFAULT 'FREE' NOT NULL;
ALTER TABLE users ADD COLUMN storage_limit BIGINT DEFAULT 5368709120 NOT NULL;
ALTER TABLE users ADD COLUMN razorpay_customer_id VARCHAR(255);
ALTER TABLE users ADD COLUMN razorpay_subscription_id VARCHAR(255);
